spring:
  application:
    name: bakeryback
  datasource:
    url: jdbc:postgresql://postgres:5432/url_shortener_db
#    url: jdbc:postgresql://192.168.99.101:30230/url_shortener_db
    username: user
    password: parool5
    driverClassName: org.postgresql.Driver
    test-while-idle: true
    validation-query: SELECT 1
    time-between-eviction-runs-millis: 60000

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html